### ISSUE TITLE
TyP3COd3 overall design

### ISSUE THREAD

**Issue by ankingcodes** [ankingcodes/TyP3C0d3#3]
This is supposed to be a typing platform meant for an audience of programmers. We also want it to be a social platform, where users can create their accounts and have high scores which shall be displayed on a leaderboard. Although, I'm still looking for ideas to determine how the ranks of each user would be decided.
Some immediate features that come to mind: 
- [ ] Landing page , describing the website
- [ ] Authentication page for registering users
- [ ] Code editor : This matters a lot because different ones have different use cases
- [ ] Database: Mongo or Postgresql
- [ ] How code should be uploaded by users ? How would they use private code ? Should we persist that code ?
- [ ] More premium ideas

**Comment by ankingcodes** [comment]
@rekib0023 Let's talk about these here. Since this project is in idea phase, I'd like to know ur plans on implementing this.

**Comment by ankingcodes** [comment]
Regarding the user experience while coding on the site, some important things to consider are:
- how would mistypes and correct types be caught ? should we stick to highlighting specific characters as in typing.io ? 
- Would we skip comments and other metadata on code during the typing experience ?
- After finding the WPM of an user, what should be an algorithm to devise the score which would be used for rank ?

**Comment by rekib0023** [comment]
> 
> 
> @rekib0023 Let's talk about these here. Since this project is in idea phase, I'd like to know ur plans on implementing this.

Ok, so about the code editor, we would need to embed it within the website right. Will the users be given options to choose between languages? If so, how to integrate the compilers for it?

**Comment by rekib0023** [comment]
Ranking the users can be done by setting up competitions for all the users. And whosoever codes faster in those competitions should be ranked accordingly. Along with these global competitions, the website may have custom practice section to work on their skills.

**Comment by ankingcodes** [comment]
@rekib0023 I think you got it wrong here, but let me explain it. The idea is that there shall be a code editor, and there should be code loaded in it. Then the user will practice his typing skill by typing over that code, while our matcher will match if the character typed by an user has matched to that on the screen. If matches, move on else backspace and correct.

**Comment by rekib0023** [comment]
atchaa.. I got you now... Sorry, had something else going on.

**Comment by ankingcodes** [comment]
> Ranking the users can be done by setting up competitions for all the users. 

That's a good idea, but that could be done monthly. What I am thinking is users can type as much they want and ranking would be based on high scores

**Comment by rekib0023** [comment]
I think, we should skip the comments and metadata as of now. People mainly are focused in improving their coding time, comments and metadata are more on the abstract sides.

**Comment by rekib0023** [comment]
Ok, now to catch the inputs. Have you got any idea on it?

**Comment by ankingcodes** [comment]
> Have you got any idea on it?

Catching inputs shall be easy, we have a javascript method called `onKeyPress()` which can register a key press, after that we just need to find the charCode of key pressed. I think current version supports this.

**Comment by ankingcodes** [comment]
If you're familiar with how react works, we also need a react component as a code editor. I'm currently using something called Monaco, but I definitely wanna shift off that because, 
a. It is developed by microsoft
b. It is poor

**Comment by rekib0023** [comment]
Yup I am familiar with react

**Comment by rekib0023** [comment]
If the code editor can be a react component, we may use React Hooks to catch and match the inputs

**Comment by ankingcodes** [comment]
Okay, proceeding with this, I believe we can do two things : 
a. Think more about code editor component 
b. Set up landing page, authentication(signup/signin) and the basic code editor.

> If the code editor can be a react component, we may use React Hooks to catch and match the inputs

Exactly, we will use our javascript method there.

**Comment by ankingcodes** [comment]
I'll create a new issue about b) and maybe we can take turns and work on it.

**Comment by rekib0023** [comment]
Sure thing !!!

**Comment by rekib0023** [comment]
Yeah for authentication, what methods are you planning to use? And also what database?

**Comment by rekib0023** [comment]
> 
> 
> I'll create a new issue about b) and maybe we can take turns and work on it, by making PRs

Okayy !!!
