### ISSUE TITLE
Landing page + Authentication

### ISSUE THREAD

**Issue by ankingcodes** [ankingcodes/TyP3C0d3#4]
- [ ] Landing page describing how the website works
- [ ] Basic backend for signup/signin along basic frontend

**Comment by ankingcodes** [comment]
@rekib0023 The backend I'm thinking of is a MongoDB database along with using something like ExpressJS and if you're more adventurous, something like NestJS

**Comment by rekib0023** [comment]
Nadaa bro!! I don't know NestJS.

**Comment by rekib0023** [comment]
Organize the issues with project boards. It would be much feasible then.

**Comment by ankingcodes** [comment]
>  I don't know NestJS.

No problem. Anything works for me.

**Comment by ankingcodes** [comment]
But these are the first two things to be accomplished before all the other work.

**Comment by rekib0023** [comment]
Sayy

**Comment by rekib0023** [comment]
> 
> 
> But these are the first two things to be accomplished before all the other work.
> Let's send in PRs whenever possible. I'll try to review ur PRs soon

Okayyyy!!!!!

**Comment by ankingcodes** [comment]
@rekib0023 Have you made any progress on the issue ? If so, make a PR and I'd like to review your work else let me know if you're busy.

**Comment by rekib0023** [comment]
yes, I just caught up with some work lately. I am now working on the UI for the site. Will let you now once I am done with it.

**Comment by rekib0023** [comment]
Do you have any name for the website?
